clear
clc
% Detailed Solution Analysis for Questions 2-5
% This MATLAB script provides a detailed comparison of the solutions for Questions 2-5.
% Each question is analyzed step-by-step to highlight specific areas where partial credit
% could be argued if points were deducted.

%% Question 2: Initial Value Problem (5 Marks)
disp('Question 2: Initial Value Problem (5 Marks)')
disp('Problem Recap:')
disp('Solve the initial value problem:')
disp('    x^3 * t * dx/dt = t^4 + x^4,    x(1) = 4.')
disp('The hint suggests dividing by x^3 * t.')
disp(' ')

disp('Ideal Solution Outline:')
disp('1. Divide by x^3 * t:')
disp('   dx/dt = (t^3 / x^3) + (x / t).')
disp('2. Substitute Z = x/t:')
disp('   Differentiate x = Z * t with respect to t to obtain dx/dt = Z + t * dZ/dt.')
disp('3. Rewrite in Terms of Z:')
disp('   Substitute back into the differential equation and simplify.')
disp('4. Integrate and Apply Initial Condition:')
disp('   After separation, integrate both sides and apply x(1) = 4 to find the constant of integration.')
disp(' ')

disp('Comparison to My Solution:')
disp('1. Correct Initial Steps: Dividing by x^3 * t (1-2 Points)')
disp('   Argument: Since this step shows understanding of the initial setup, I argue for 1-2 points.')
disp('2. Substitution Attempt and Complexity in Simplification (1 Point)')
disp('   Argument: I attempted a logical substitution which set up the integral and shows partial understanding, ')
disp('   deserving at least 0.5 credit for effort in simplifying, even if it led to a complex form.')
disp('3. Persistence in Trying Integration Techniques (1 Point)')
disp('   Argument: Demonstrated problem-solving persistence by attempting integration by parts and exploring multiple methods, ')
disp('   which shows a partial understanding of differential equation techniques. Requesting 0.5 additional point.')

%% Question 3: Exact ODE (5 Marks)
disp(' ')
disp('Question 3: Exact ODE (5 Marks)')
disp('Problem Recap:')
disp('Solve the differential equation:')
disp('    (z + y) * dz/dy = y - z.')
disp('This equation suggests testing for exactness and, if not exact, using an integrating factor or substitution.')
disp(' ')

disp('Ideal Solution Outline:')
disp('1. Rewrite and Test for Exactness:')
disp('   Rearrange as M(y, z) + N(y, z) * dz/dy = 0, where M(y, z) = y - z and N(y, z) = z + y.')
disp('2. Find an Integrating Factor:')
disp('   If not exact, find an integrating factor, possibly dependent on z + y.')
disp('3. Solve After Applying Integrating Factor:')
disp('   Multiply through, recheck for exactness, and solve the equation.')
disp(' ')

disp('Comparison to My Solution:')
disp('1. Checking for Exactness (1 Point)')
disp('   Argument: I correctly identified M(y, z) and N(y, z) and checked for exactness, showing understanding, and argue for 1 point.')
disp('2. Attempt to Find Integrating Factor and Alternative Methods (1-2 Points)')
disp('   Argument: I explored integrating factors and alternative solutions despite challenges, showing persistence. Arguement for for 1-2 points.')
disp('3. Substitutions and Persistence (1 Point)')
disp('   Argument: Tried substitutions to simplify, reflecting a partial understanding and I request an additional point.')

%% Question 4: Linear ODE (5 Marks)
disp(' ')
disp('Question 4: Linear ODE (5 Marks)')
disp('Problem Recap:')
disp('Solve the linear ODE:')
disp('    dx/dt + 2(cot 2t) * x = cos 2t.')
disp('The hint suggests the substitution z = sin 2t.')
disp(' ')

disp('Ideal Solution Outline:')
disp('1. Recognize Linear Form and Integrate Factor:')
disp('   dx/dt + P(t)x = Q(t), with P(t) = 2 cot 2t, Q(t) = cos 2t.')
disp('2. Multiply by Integrating Factor and Integrate:')
disp('   Transform to d/dt (x * sin 2t), then integrate both sides.')
disp('3. Write Final Solution by Dividing by sin 2t.')
disp(' ')

disp('Comparison to My Solution:')
disp('1. Identifying Linear Form and Integrating Factor (1 Point)')
disp('   Argument: Correct setup and transformation by integrating factor, argue for 1 point.')
disp('2. Multiplying by Integrating Factor and Setting Up Integration (1-2 Points)')
disp('   Argument: Transformation aligns with ideal solution, worth 1-2 points.')
disp('3. Attempted Integration and Final Answer (1-2 Points)')
disp('   Argument: Effort in setup and integration, partial credit for persistence.')
disp('4. Final Answer Form and Simplification (Potential Half-Point)')
disp(['   Argument: Although the solution is not fully simplified, the overall path shows an understanding of the structure and method. ', ...
      'Requesting a half-point if the final answer was heavily penalized, I essentially followed the logical approach up to the simplification stage.'])

%% Question 5: General Solution for ODE (6 Marks)
disp(' ')
disp('Question 5: General Solution for ODE (6 Marks)')
disp('Problem Recap:')
disp('Solve the ODE by finding the characteristic equation:')
disp('    d^4x/dt^4 - 3 * d^3x/dt^3 - 5 * d^2x/dt^2 + 9 * dx/dt - 2x = 0.')
disp('Factor the characteristic equation, and solve the general solution with non-homogeneous terms.')
disp(' ')

disp('Ideal Solution Outline:')
disp('1. Find Characteristic Equation:')
disp('   Substitute x = e^(mt), simplify to find the characteristic polynomial.')
disp('2. Solve Roots and Write x_h(t):')
disp('   Solve the polynomial roots and construct the homogeneous solution.')
disp('3. Find Particular Solution:')
disp('   Use undetermined coefficients for non-homogeneous terms.')
disp('4. Combine x_h(t) and x_p(t) for Final Solution.')
disp(' ')

disp('Comparison to My Solution:')
disp('1. Setting Up the Characteristic Equation (2 Points)')
disp('   Argument: Correct substitution and factorization, argue for 2 points.')
disp('2. Solving Roots and Writing x_h(t) (1-2 Points)')
disp('   Argument: Correct use of roots for x_h(t), worth 1-2 points.')
disp('3. Attempting Particular Solution x_p(t) (1-2 Points)')
disp('   Argument: Correct setup for x_p(t), reflects partial understanding.')
disp('4. Combining x_h(t) and x_p(t) (0.5-1 Point)')
disp('   Argument: Final structure correct, request partial credit for final solution structure, even though not fully solved.')

% James-Edward Gray
% Student ID: 21015159
